<?php

/**************************************************************************
 * PokedexsRepository.php, pokemon Android
 *
 * Copyright 2016
 * Description : 
 * Author(s)   : Harmony
 * Licence     : 
 * Last update : Jul 21, 2016
 *
 **************************************************************************/

namespace Pokemon\ApiBundle\Repository;

use Pokemon\ApiBundle\Repository\PokedexsRepositoryBase;

/**
 * Pokedexs Repository
 *
 * This class was generated by the Harmony / Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokedexsRepository extends PokedexsRepositoryBase {

}

?>
